accounts/urls.py
from django.urls import path

from accounts import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("clipper/", views.ClipperLoginView.as_view(), name="clipper"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("create/", views.CreateAccountView.as_view(), name="create"),
    path("update/", views.UpdateAccountView.as_view(), name="update"),
    path("delete/", views.DeleteConfirmView.as_view(), name="delete"),
    path("delete/final", views.DeleteFinalView.as_view(), name="delete_final"),
    path("change_password/", views.UpdatePasswordView.as_view(), name="change_password"),
    path(
        "activate/<uidb64>/<token>/",
        views.ActivateAccountView.as_view(),
        name="activate",
    ),
    path("password_reset/", views.ResetPasswordView.as_view(), name="password_reset"),
    path(
        "password_reset/<uidb64>/<token>/",
        views.ResetPasswordConfirmView.as_view(),
        name="password_reset_confirm",
    ),
]

admin_pages/urls.py
from django.urls import path

from admin_pages import views
from site_settings.models import ENS

urlpatterns = [
    path("", views.AdminView.as_view(), name="index"),
    path("info", views.SiteInfo.as_view(), name="info"),
    path("export/activities/", views.ExportActivities.as_view(), name="activities.csv"),
    path("export/slots/", views.ExportSlots.as_view(), name="slots.csv"),
    path("import/activity_choices/", views.CSV_UploadView.as_view(), name="csv_upload"),
    path(
        "export/participants/",
        views.ExportParticipants.as_view(),
        name="participants.csv",
    ),
    path(
        "export/participants/ulm",
        views.ExportParticipants.as_view(school=ENS.ENS_ULM),
        name="participants_ulm.csv",
    ),
    path(
        "export/participants/lyon",
        views.ExportParticipants.as_view(school=ENS.ENS_LYON),
        name="participants_lyon.csv",
    ),
    path(
        "export/participants/rennes",
        views.ExportParticipants.as_view(school=ENS.ENS_RENNES),
        name="participants_rennes.csv",
    ),
    path(
        "export/participants/saclay",
        views.ExportParticipants.as_view(school=ENS.ENS_CACHAN),
        name="participants_saclay.csv",
    ),
    path(
        "export/activity_choices/",
        views.ExportActivityChoices.as_view(),
        name="activity_choices.csv",
    ),
    path(
        "email/send_user_emails_0564946523/",
        views.SendUserEmail.as_view(),
        name="email_users",
    ),
    path(
        "email/send_orga_emails_5682480453/",
        views.SendOrgaEmail.as_view(),
        name="email_orgas",
    ),
    path(
        "email/send_orga_planning_emails_56983345621/",
        views.SendOrgaPlanningEmail.as_view(),
        name="email_orgas_planning",
    ),
    path("email/new_email/", views.NewEmail.as_view(), name="email_new"),
]

home/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.views.generic import RedirectView

from home import views

sitemaps = {"static_pages": views.StaticViewSitemap}

urlpatterns = [
    path("inscription/", views.RegisterView.as_view(), name="inscription"),
    path("desinscription/", views.UnregisterView.as_view(), name="desinscription"),
    path(
        "activites/nouvelle/",
        views.ActivitySubmissionView.as_view(),
        name="activity_submission",
    ),
    path("profil/", views.ProfileView.as_view(), name="profile"),
    path("favicon.ico", RedirectView.as_view(url="/static/imgs/favicon.ico")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path(
        "admin_pages/",
        include(("admin_pages.urls", "admin_pages"), namespace="admin_pages"),
    ),
    path("comptes/", include("accounts.urls")),
    path("robots.txt", views.TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

interludes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("", include("pages.urls")),
]

site_settings/models.py
from datetime import date, timedelta
from pathlib import Path
from typing import Callable, Optional, Type, TypeVar

from django.core.cache import cache
from django.core.files.storage import FileSystemStorage
from django.db import models
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _


def get_year() -> int:
    """Return current school year:
    if between august and december, that is the current year + 1"""
    date = now()
    year = date.year
    if date.month >= 8:
        year += 1
    return year


class Colors(models.TextChoices):
    """Couleur d'affichage dans le planning
    Leur code HTML est hardcodé dans la template '_planning.html'."""

    RED = "a", "Rouge"
    ORANGE = "b", "Orange"
    YELLOW = "c", "Jaune"
    GREEN = "d", "Vert"
    BLUE = "e", "Bleu"
    DARK_BLUE = "f", "Bleu foncé"
    BLACK = "g", "Noir"


class OverwriteStorage(FileSystemStorage):
    """used to enforcing a fixed filename to upload file
    This allow for a constant link to a changeable file"""

    filename: str

    def __init__(self, filename: str = "file") -> None:
        """Filename without extension"""
        super().__init__()
        self.filename = filename

    def get_available_name(self, name: str, max_length: Optional[int] = None) -> str:
        """
        Returns a filename that's free on the target storage system, and
        available for new content to be written to.
        """
        # If the filename already exists, remove it as if it was a true file system
        extension = Path(name).suffix
        new_name = self.filename + extension
        if self.exists(new_name):
            self.delete(new_name)
        return super(FileSystemStorage, self).get_available_name(new_name, max_length)


T = TypeVar("T", bound="SingletonModel")


class SingletonModel(models.Model):
    """Table de la BDD qui ne possède qu'un seul élément"""

    class Meta:
        abstract = True

    def save(self, *args, **kwargs) -> None:
        """save the unique element"""
        self.pk = 1  # set private key to one
        super(SingletonModel, self).save(*args, **kwargs)
        self.set_cache()

    def delete(self, *args, **kwargs):
        """can't delete the unique element"""
        raise ValueError("Attempting to delete unique element")

    @classmethod
    def load(cls: Type[T]) -> T:
        """load and return the unique element"""
        if cache.get(cls.__name__) is None:
            obj, created = cls.objects.get_or_create(pk=1)
            if not created:
                obj.set_cache()
        return cache.get(cls.__name__)  # type: ignore

    def set_cache(self) -> None:
        """save in cache to limit db requests"""
        cache.set(self.__class__.__name__, self)


class ENS(models.TextChoices):
    """enum representant les ENS"""

    ENS_ULM = "U", _("ENS Ulm")
    ENS_LYON = "L", _("ENS Lyon")
    ENS_RENNES = "R", _("ENS Rennes")
    ENS_CACHAN = "C", _("ENS Paris Saclay")

    def adjective(self) -> str:
        if self == "C":
            return "saclaysien"
        elif self == "L":
            return "lyonnais"
        elif self == "R":
            return "rennais"
        return "ulmite"

    def adjective_plural(self) -> str:
        if self == "C":
            return "saclaysiens"
        elif self == "L":
            return "lyonnais"
        elif self == "R":
            return "rennais"
        return "ulmites"


MEALS = [
    "friday_evening",
    "saturday_morning",
    "saturday_midday",
    "saturday_evening",
    "sunday_morning",
    "sunday_midday",
    "sunday_evening",
]

MEALS_FR = [
    "vendredi soir",
    "samedi matin",
    "samedi midi",
    "samedi soir",
    "dimanche matin",
    "dimanche midi",
    "dimanche soir",
]

OPTIONS = [
    "option1",
    "option2",
    "option3",
    "option4",
    "option5",
]


class SiteSettings(SingletonModel):
    """Réglages globaux du site

    SI VOUS AJOUTEZ DES RÉGLAGES, PENSEZ À LES RAJOUTER AUSSI DANS LES fieldsets
    DE admin.py, SINON IL N'Y APPARAITRONT PAS...
    """

    contact_email = models.EmailField("Email contact", blank=True, null=True)
    hosting_school = models.CharField(
        "École hébergeant l'événement", max_length=1, choices=ENS.choices, default=ENS.ENS_ULM
    )
    ticket_url = models.URLField(
        "Lien billeterie",
        max_length=300,
        blank=True,
        null=True,
    )

    date_start = models.DateField("Date de début", blank=True, null=True)
    date_end = models.DateField("Date de fin", blank=True, null=True)

    price_entry_unpaid = models.DecimalField(
        "prix d'inscription (non-salarié)", decimal_places=2, max_digits=5, default=0
    )
    price_entry_paid = models.DecimalField("prix d'inscription (salarié)", decimal_places=2, max_digits=5, default=0)

    price_sleep_unpaid = models.DecimalField(
        "prix d'hébergement (non-salarié)", decimal_places=2, max_digits=5, default=0
    )
    price_sleep_paid = models.DecimalField("prix d'hébergement (salarié)", decimal_places=2, max_digits=5, default=0)

    price_friday_evening_meal_unpaid = models.DecimalField(
        "prix du repas du vendredi soir (non-salarié)",
        decimal_places=2,
        max_digits=5,
        default=0,
    )
    price_friday_evening_meal_paid = models.DecimalField(
        "prix du repas du vendredi soir (salarié)",
        decimal_places=2,
        max_digits=5,
        default=0,
    )

    price_saturday_morning_meal_unpaid = models.DecimalField(
        "prix du repas du samedi matin (non-salarié)",
        decimal_places=2,
        max_digits=5,
        default=0,
    )
    price_saturday_morning_meal_paid = models.DecimalField(
        "prix du repas du samedi matin (salarié)",
        decimal_places=2,
        max_digits=5,
        default=0,
    )

    price_saturday_midday_meal_unpaid = models.DecimalField(
        "prix du repas du samedi midi (non-salarié)",
        decimal_places=2,
        max_digits=5,
        default=0,
    )
    price_saturday_midday_meal_paid = models.DecimalField(
        "prix du repas du samedi midi (salarié)",
        decimal_places=2,
        max_digits=5,
        default=0,
    )

    price_saturday_evening_meal_unpaid = models.DecimalField(
        "prix du repas du samedi soir (non-salarié)",
        decimal_places=2,
        max_digits=5,
        default=0,
    )
    price_saturday_evening_meal_paid = models.DecimalField(
        "prix du repas du samedi soir (salarié)",
        decimal_places=2,
        max_digits=5,
        default=0,
    )

    price_sunday_morning_meal_unpaid = models.DecimalField(
        "prix du repas du dimanche matin (non-salarié)",
        decimal_places=2,
        max_digits=5,
        default=0,
    )
    price_sunday_morning_meal_paid = models.DecimalField(
        "prix du repas du dimanche matin (salarié)",
        decimal_places=2,
        max_digits=5,
        default=0,
    )

    price_sunday_midday_meal_unpaid = models.DecimalField(
        "prix du repas du dimanche midi (non-salarié)",
        decimal_places=2,
        max_digits=5,
        default=0,
    )
    price_sunday_midday_meal_paid = models.DecimalField(
        "prix du repas du dimanche midi (salarié)",
        decimal_places=2,
        max_digits=5,
        default=0,
    )

    price_sunday_evening_meal_unpaid = models.DecimalField(
        "prix du repas du dimanche soir (non-salarié)",
        decimal_places=2,
        max_digits=5,
        default=0,
    )
    price_sunday_evening_meal_paid = models.DecimalField(
        "prix du repas du dimanche soir (salarié)",
        decimal_places=2,
        max_digits=5,
        default=0,
    )

    option1_enable = models.BooleanField(
        "Option 1",
        default=False,
    )
    option1_description = models.CharField(
        "Description Option 1",
        blank=True,
        null=True,
        help_text="ex: 'Adhérent du COF', 'Commande un Mug'...",
        max_length=200,
    )
    price_option1_paid = models.DecimalField(
        "prix option 1 (salarié)",
        decimal_places=2,
        max_digits=5,
        default=0,
    )
    price_option1_unpaid = models.DecimalField(
        "prix option 1 (non-salarié)",
        decimal_places=2,
        max_digits=5,
        default=0,
    )

    option2_enable = models.BooleanField(
        "Option 2",
        default=False,
    )
    option2_description = models.CharField(
        "Description Option 2",
        blank=True,
        null=True,
        max_length=200,
    )
    price_option2_paid = models.DecimalField(
        "prix option 2 (salarié)",
        decimal_places=2,
        max_digits=5,
        default=0,
    )
    price_option2_unpaid = models.DecimalField(
        "prix option 2 (non-salarié)",
        decimal_places=2,
        max_digits=5,
        default=0,
    )

    option3_enable = models.BooleanField(
        "Option 3",
        default=False,
    )
    option3_description = models.CharField(
        "Description Option 3",
        blank=True,
        null=True,
        max_length=200,
    )
    price_option3_paid = models.DecimalField(
        "prix option 3 (salarié)",
        decimal_places=2,
        max_digits=5,
        default=0,
    )
    price_option3_unpaid = models.DecimalField(
        "prix option 3 (non-salarié)",
        decimal_places=2,
        max_digits=5,
        default=0,
    )

    option4_enable = models.BooleanField(
        "Option 4",
        default=False,
    )
    option4_description = models.CharField(
        "Description Option 4",
        blank=True,
        null=True,
        max_length=200,
    )
    price_option4_paid = models.DecimalField(
        "prix option 4 (salarié)",
        decimal_places=2,
        max_digits=5,
        default=0,
    )
    price_option4_unpaid = models.DecimalField(
        "prix option 4 (non-salarié)",
        decimal_places=2,
        max_digits=5,
        default=0,
    )

home/templates/base.html
{% spaceless %}
{% load static %}
<!doctype html>
<html lang="fr">

<head>
	<!-- WEBSITE VERSION {{ constants.WEBSITE_FULL_VERSION }} -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<title>{% block title %}Interludes{% if settings.date_start %} {{ settings.date_start.year }}{% endif %}{% endblock %}</title>
		<meta name="description" content="Inscriptions et infos sur les interENS ludiques{% if settings.date_start %}, édition {{ settings.date_start.year }}{% endif %}">
		<meta name="keywords" content="Interludes ENS {% if settings.date_start %}{{ settings.date_start.year }} {% endif %}InterENS">
		{% if settings.favicon %}
		<link rel="icon" type="image/png" href="{{ settings.favicon.url }}">
		{% endif %}

		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}?v={{ constants.CSS_VERSION }}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome-all.min.css' %}">
		{% block head %}{% endblock %}
	</head>

	<body>
		<header>
			<div id="header_logo"  class="easter_egg">
				<h1><a href="/">
					{% if settings.logo %}<img src="{{ settings.logo.url }}">&nbsp;{% endif %}
					Interludes{% if settings.date_start %} {{ settings.date_start.year }}{% endif %}&nbsp;</a></h1>
			</div>
			<div id="head_main_infos">
			<div id="location">
				{% if settings.hosting_school %}
				{{ settings.get_hosting_school_display }}
				{% else %}
					École non-fixée
				{% endif %}
			</div>
			<div id="date">{% if settings.date_start %}
				{% if settings.date_end %}
				{% if settings.date_end.month != settings.date_start.month %}
				{{ settings.date_start|date:"j N" }}-{{ settings.date_end|date:"j N Y" }}
				{% else %}
				{{ settings.date_start.day }}-{{ settings.date_end }}
				{% endif %}
				{% else %}
				{{ settings.date_start }}
				{% endif %}
				{% else %}
				Date non-fixée
				{% endif %}</div>
			</div>
		</header>

		<script type="text/javascript">
			function toggle_menu() {
				var nav = document.getElementById("nav");
				if (nav.className === "") {
					nav.className += "responsive";
				} else {
					nav.className = "";
				}
			}
		</script>

		<nav id="nav">
			<a href="{% url 'home' %}" rel="text/html"
				class="{% block nav_home %}{% endblock %}">
				Accueil
			</a>
			<a href="{% url 'inscription' %}" rel="text/html"
				class="{% block nav_inscription %}{% endblock %}">
				Inscriptions
			</a>
			<a href="{% url 'html_page' slug='activites' %}" rel="text/html"
				class="{% block nav_activite %}{% endblock %}">
				Activités
			</a>
			<a href="{% url 'html_page' slug='faq' %}" rel="text/html"
				class="{% block nav_faq %}{% endblock %}">
				FAQ
			</a>
			{% if request.user.is_authenticated %}
				<a href="{% url 'profile' %}"
					class="{% block nav_profile %}{% endblock %}">
					Mon compte
				</a>
			{% else %}
				<a href="{% url 'accounts:login' %}"
					class="{% block nav_login %}{% endblock %}">
					Connexion
				</a>
			{% endif %}
			{% if user.is_superuser %}
			<a href="{% url 'admin_pages:index' %}"
				class="{% block nav_admin %}{% endblock %}">
				Administration
			</a>
			{% endif %}
			<a href="javascript:void(0);" class="icon" onclick="toggle_menu()">
				<i class="fa fa-bars"></i>
			</a>
		</nav>

		<main>
			{% if messages %}
			<ul class="messagelist">
				{% for message in messages %}
					<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
				{% endfor %}
			</ul>
			{% endif %}
			{% if settings.global_message %}
				{% if settings.global_message_as_html %}
					{{ settings.global_message|safe }}
				{% else %}
					<ul class="messagelist"><li class="info">{{ settings.global_message }}</li></ul>
				{% endif %}
			{% endif %}

			{% block "content" %}
			{% endblock %}
		</main>

	<footer>
		<div id="sponsors">
			{% for sponsor in sponsors %}
			<a class="external" href="{{ sponsor.url }}">
				<img src="{{ sponsor.image.url }}"
					alt="{{ sponsor.alt_text }}"
					title="{{ sponsor.alt_text }}"
				/>
			</a>
			{% endfor %}
		</div>
		<p>
			{% if settings.contact_email %}
			Pour tout problème, contacter&nbsp;:<br><span class="antispam">{{ settings.contact_email_reversed }}</span>
			<br>
			{% endif %}
			<a href="{% url 'html_page' slug='legal' %}">Mentions légales</a>
		</p>
	</footer>

	</body>

</html>
{% endspaceless %}

home/templates/profile.html
{% extends "base.html" %}

{% block nav_profile %}current{% endblock %}

{% block "content" %}

<h2>Mon compte</h2>

<p>Connecté en tant que {{ user.first_name }} {{ user.last_name }} ({{ user.email }})</p>

{% if user.is_superuser %}
<ul class="messagelist">
<li class="info">
	Vous avez les droits d'administrateurs.
	<br>Aller à la <a href="{% url 'admin_pages:index' %}">page d'administration du site</a>
	{% if user.is_staff %}
	<br>Aller à la <a href="{% url 'admin:index' %}">page d'administration de Django</a>
	(N'y modifier rien si vous n'êtes pas sûrs de vous)
	{% endif %}
</li>
</ul>{% endif %}

{% if user.profile.is_registered %}
	<strong>Mon inscription&nbsp;:</strong>
	{% if settings.inscriptions_open and settings.inscriptions_end %}
	  modifiable jusqu'au {{ settings.inscriptions_end|date:"l d F Y à H:i" }}
	{% endif %}
	<ul>
		<li>Tarif personnalisé : {{ user.profile.cost }}&nbsp;€</li>
		<li>{% if user.profile.sleeps %}Inscrit pour dormir sur place{% else %}Non inscrit pour dormir sur place{% endif %}</li>
		{% comment "pas de tasse" %}<li>{% if user.profile.mug %}Commandse une tasse{% else %}Ne commande pas de tasse{% endif %}</li>{% endcomment%}
		{% if user.profile.nb_meals != 0 %}
		<li>Inscrit à {{ user.profile.nb_meals }} repas&nbsp;:</li>
			<ul>
				{% if settings.meal_friday_evening and user.profile.meal_friday_evening %}<li>Vendredi soir</li>{% endif %}
				{% if settings.meal_saturday_morning and user.profile.meal_saturday_morning  %}<li>Petit dej' du samedi</li>{% endif %}
				{% if settings.meal_saturday_midday and user.profile.meal_saturday_midday  %}<li>Samedi midi</li>{% endif %}
				{% if settings.meal_saturday_evening and user.profile.meal_saturday_evening  %}<li>Samedi soir</li>{% endif %}
				{% if settings.meal_sunday_morning and user.profile.meal_sunday_morning  %}<li>Petit dej' du dimanche</li>{% endif %}
				{% if settings.meal_sunday_midday and user.profile.meal_sunday_midday  %}<li>Dimanche midi</li>{% endif %}
				{% if settings.meal_sunday_evening and user.profile.meal_sunday_evening  %}<li>Dimanche soir (à emporter)</li>{% endif %}
			</ul>
		{% else %}
		<li>Inscrit à aucun repas.</li>
		{% endif %}
		{% if settings.option1_enable or settings.option2_enable or settings.option3_enable or settings.option4_enable or settings.option5_enable %} 
		{% if user.profile.option1 or user.profile.option2 or user.profile.option3 or user.profile.option4 or user.profile.option5 %} 
		<li>
			Options&nbsp;:
			<ul>
			{% if settings.option1_enable %}<li>{{ settings.option1_description }}</li>{% endif %}
			{% if settings.option2_enable %}<li>{{ settings.option2_description }}</li>{% endif %}
			{% if settings.option3_enable %}<li>{{ settings.option3_description }}</li>{% endif %}
			{% if settings.option4_enable %}<li>{{ settings.option4_description }}</li>{% endif %}
			{% if settings.option5_enable %}<li>{{ settings.option5_description }}</li>{% endif %}
			</ul>
		</li>
		{% endif %}
		{% endif %}
		{% if settings.activities_allocated %}
			{% if my_choices %}
			<li>Inscrit&middot;e à {{ my_choices|length }} activités&nbsp;:
				<ul>
					{% for choice in my_choices %}
					<li><a href="{% url 'html_page' slug='activites' %}#{{ choice.slot.activity.slug }}">{{ choice.slot }}</a>
						{% if choice.slot.on_planning %}
							(le {{ choice.slot.start|date:"l à H:i" }}<!--  en {{ choice.slot.room }} -->)
						{% endif %}
					</li>
					{% endfor %}
				</ul>
			</li>
			{% else %}
			<li>Inscrit&middot;e à aucune activité</li>
			{% endif %}
		{% else %}
			{% if my_choices %}
			<li>{{ my_choices|length }} activités souhaitées&nbsp;:
				<ol>
					{% for choice in my_choices %}
					<li><a href="{% url 'html_page' slug='activites' %}#{{ choice.slot.activity.slug }}">{{ choice.slot }}</a>
						{% if choice.slot.on_planning %}
							(le {{ choice.slot.start|date:"l à H:i" }}<!--  en {{ choice.slot.room }} -->)
						{% endif %}
					</li>
					{% endfor %}
				</ol>
			</li>
			{% else %}
			<li>Aucune activité souhaitée</li>
			{% endif %}

		{% endif %}
	</ul>
{% else %}
	<strong>Vous n'êtes pas inscrit à l'évènement.</strong>

	{% if not settings.inscriptions_open %}
		{% if settings.inscriptions_not_open_yet %}
			<p>Les inscriptions aux activités ne sont pas encore ouvertes. Elles ouvriront le <strong>{{ settings.inscriptions_start|date:"l d F Y à H:i" }}</strong>.</p>
		{% elif settings.inscriptions_have_closed %}
			<p>Les inscriptions aux activités sont fermées.</p>
		{% else %}
			<p>Les inscriptions aux activités ne sont pas encore ouvertes ou ont été fermées.</p>
		{% endif %}
	{% elif settings.inscriptions_end %}
		<p>les inscriptions aux activités sont ouvertes jusqu'au {{ settings.inscriptions_end|date:"l d F Y à H:i" }}).</p>
	{% endif %}
	<br><br>
{% endif %}

<div class="flex wrap">
	{% if user.profile.is_registered %}
		{% if settings.inscriptions_open %}
		<a class="button" href="{% url 'desinscription' %}">Me désinscrire</a>
		<a class="button" href="{% url 'inscription' %}">Modifier mon inscription</a>
		{% else %}
		<script type="text/javascript">
			function clicked() {
				if (confirm(
					'Les inscriptions étant fermées, vous ne pourrez pas vous réinscrire.\nVoulez vous vraiment vous désinscrire?'
				))
					window.location = "{% url 'desinscription' %}";
			}
		</script>
		<button class="button" onclick="clicked();">Me désinscrire</button>
		{% endif %}
	{% elif settings.inscriptions_open %}
	<a class="button" href="{% url 'inscription' %}">S'inscrire</a>
	{% endif %}

	<a class="button" href="{% url 'accounts:update' %}">Modifier mes informations</a>
	<a class="button" href="{% url 'accounts:logout' %}">Déconnexion</a>
</div>
<div class="flex wrap"><a class="red button" href="{% url 'accounts:delete' %}">Supprimer mon compte</a></div>

{% endblock %}