accounts/urls.py
from django.urls import path

from accounts import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("clipper/", views.ClipperLoginView.as_view(), name="clipper"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("create/", views.CreateAccountView.as_view(), name="create"),
    path("update/", views.UpdateAccountView.as_view(), name="update"),
    path("delete/", views.DeleteConfirmView.as_view(), name="delete"),
    path("delete/final", views.DeleteFinalView.as_view(), name="delete_final"),
    path("change_password/", views.UpdatePasswordView.as_view(), name="change_password"),
    path(
        "activate/<uidb64>/<token>/",
        views.ActivateAccountView.as_view(),
        name="activate",
    ),
    path("password_reset/", views.ResetPasswordView.as_view(), name="password_reset"),
    path(
        "password_reset/<uidb64>/<token>/",
        views.ResetPasswordConfirmView.as_view(),
        name="password_reset_confirm",
    ),
]

home/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.views.generic import RedirectView

from home import views

sitemaps = {"static_pages": views.StaticViewSitemap}

urlpatterns = [
    path("inscription/", views.RegisterView.as_view(), name="inscription"),
    path("desinscription/", views.UnregisterView.as_view(), name="desinscription"),
    path(
        "activites/nouvelle/",
        views.ActivitySubmissionView.as_view(),
        name="activity_submission",
    ),
    path("profil/", views.ProfileView.as_view(), name="profile"),
    path("favicon.ico", RedirectView.as_view(url="/static/imgs/favicon.ico")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path(
        "admin_pages/",
        include(("admin_pages.urls", "admin_pages"), namespace="admin_pages"),
    ),
    path("comptes/", include("accounts.urls")),
    path("robots.txt", views.TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

interludes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + [
    path("admin/", admin.site.urls),
    path("", include("home.urls")),
    path("", include("pages.urls")),
]

accounts/forms.py
from typing import Any, Optional

from django import forms
from django.contrib.auth import authenticate, password_validation
from django.contrib.auth.forms import (
    AuthenticationForm,
    PasswordResetForm,
    UserCreationForm,
)
from django.utils.safestring import mark_safe

from accounts.models import EmailUser
from shared.forms import FormRenderMixin
from shared.models import normalize_email


def password_criterions_html() -> str:
    """Wraps password criterions into nice html used by other forms"""

    def wrap_str(s, tagopen: str, tagclose: Optional[str] = None) -> str:
        if not tagclose:
            tagclose = tagopen
        return "<{}>{}</{}>".format(tagopen, s, tagclose)

    criterions = password_validation.password_validators_help_texts()
    criterions_html = wrap_str(
        "\n".join(map(lambda crit: wrap_str(crit, "li"), criterions)),
        'ul class="helptext"',
        "ul",
    )
    return mark_safe(criterions_html)


class LoginForm(AuthenticationForm):
    """Form used when loging in"""

    def clean(self, *args, **kwargs):
        self.cleaned_data["username"] = normalize_email(self.cleaned_data.get("username"))  # type: ignore
        return super().clean(*args, **kwargs)


class CreateAccountForm(FormRenderMixin, UserCreationForm):
    """Form used to register a new user"""

    class Meta:
        model = EmailUser
        fields = (
            "email",
            "first_name",
            "last_name",
            "password1",
            "password2",
        )


class UpdateAccountForm(FormRenderMixin, forms.ModelForm):
    """Form used to update name/email"""

    class Meta:
        model = EmailUser
        fields = ("email", "first_name", "last_name")
        help_texts = {
            "email": "Si vous la changez, il faudra confirmer la nouvelle adresse",
        }

    def clean_email(self) -> str:
        """Check email uniqueness"""
        email = self.cleaned_data["email"]
        if email == self.instance.email:
            return email  # type: ignore
        norm_email = normalize_email(email)
        if EmailUser.objects.filter(email=norm_email).count() > 0:
            raise forms.ValidationError("Un autre compte avec cette adresse mail existe déjà.")
        return norm_email

    def save(self, commit=True) -> Any:
        email_changed = "email" in self.changed_data
        user = super().save(commit=False)
        if email_changed:
            user.email_confirmed = False
            user.is_active = False
        if commit:
            user.save()
        return user


class UpdatePasswordForm(FormRenderMixin, forms.Form):
    """Form to update one's password"""

    current_password = forms.CharField(
        widget=forms.PasswordInput,
        label="Mot de passe actuel",
    )
    password = forms.CharField(
        widget=forms.PasswordInput,
        help_text=password_criterions_html(),
        label="Nouveau mot de passe",
    )
    password_confirm = forms.CharField(
        widget=forms.PasswordInput,
        label="Nouveau mot de passe (confirmation)",
    )

    def __init__(self, *args, **kwargs) -> None:
        self.user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)

    def clean_current_password(self):
        """Check current password correctness"""
        cur_password = self.cleaned_data["current_password"]
        if authenticate(username=self.user.email, password=cur_password) != self.user:
            raise forms.ValidationError("Votre mot de passe actuel est incorrect.")
        return cur_password

    def clean_password(self):
        """Check password strength"""
        password = self.cleaned_data["password"]
        password_validation.validate_password(password)
        return password

    def clean_password_confirm(self):
        """Check that both passwords match"""
        cleaned_data = super().clean()
        if not cleaned_data:
            return
        password = cleaned_data.get("password")
        password_confirm = cleaned_data.get("password_confirm")
        if not password:
            return None
        if password != password_confirm:
            raise forms.ValidationError("Les deux mots de passe ne sont pas identiques.")
        return cleaned_data

    def apply(self):
        """Apply the password change, assuming validation was already passed"""
        self.user.set_password(self.cleaned_data["password"])
        self.user.save()


class PasswordResetEmailForm(PasswordResetForm):
    """Form used when asking email to send password reset linkk"""

    def clean(self, *args, **kwargs):
        self.cleaned_data["email"] = normalize_email(self.cleaned_data.get("email"))  # type: ignore
        return super().clean(*args, **kwargs)

accounts/views.py
from urllib.parse import urlparse, urlunparse

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import PermissionDenied
from django.http import Http404, HttpRequest
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.urls import reverse, reverse_lazy
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.views.generic import FormView, RedirectView, TemplateView, UpdateView, View

from accounts import forms
from accounts.backends import CLIPPER_SESSION_KEY, get_cas_client
from accounts.models import EmailUser
from accounts.tokens import email_token_generator
from site_settings.models import SiteSettings


def send_validation_email(request, user: EmailUser, subject: str, template: str) -> None:
    """Send a validation email to user"""
    current_site = get_current_site(request)
    message = render_to_string(
        template,
        {
            "user": user,
            "domain": current_site.domain,
            "uid": urlsafe_base64_encode(force_bytes(user.pk)),
            "token": email_token_generator.make_token(user),
        },
    )
    user.email_user(subject, message)


class LoginView(auth_views.LoginView):
    """Vue pour se connecter"""

    template_name = "login.html"
    redirect_authenticated_user = True
    redirect_url = reverse_lazy("profile")
    form_class = forms.LoginForm


class LogoutView(RedirectView):
    """Vue pour se deconnecter"""

    permanent = False
    pattern_name = "home"

    clipper_connected: bool
    message = "Vous avez bien été déconnecté·e."

    def setup(self, request: HttpRequest) -> None:
        super().setup(request)
        if CLIPPER_SESSION_KEY in request.session:
            del request.session[CLIPPER_SESSION_KEY]
            self.clipper_connected = True
        else:
            self.clipper_connected = False

    def get_redirect_url(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            logout(self.request)
        next_page = super().get_redirect_url(*args, **kwargs)
        if self.clipper_connected:
            cas_client = get_cas_client(self.request)

            # If the next_url is local (no hostname), make it absolute so that the user
            # is correctly redirected from CAS.
            if next_page is not None and not urlparse(next_page).netloc:
                request = self.request
                next_page = urlunparse((request.scheme, request.get_host(), next_page, "", "", ""))

            next_page = cas_client.get_logout_url(redirect_url=next_page)
        messages.success(self.request, self.message)
        return next_page


# ==============================
# Create Account
# ==============================


class CreateAccountView(View):
    """Vue pour la creation de compte"""

    form_class = forms.CreateAccountForm
    template_name = "create_account.html"
    email_template = "email/activation.html"

    @staticmethod
    def check_creation_allowed() -> None:
        """Vérifie que la création de compte est authorisée
        Renvoie un 404 si ce n'est pas le cas"""
        settings = SiteSettings.load()
        if not settings.registrations_open:
            raise Http404("La création de compte n'est pas ouverte actuellement")

    def get(self, request, *args, **kwargs):
        """handle get requests"""
        self.check_creation_allowed()
        form = self.form_class()
        return render(request, self.template_name, {"form": form})

    def post(self, request, *args, **kwargs):
        """handle post requests"""
        self.check_creation_allowed()
        form = self.form_class(request.POST)
        if not form.is_valid():
            messages.error(
                request,
                "Formulaire invalide. Veuillez corriger les erreurs et le renvoyer.",
            )
            return render(request, self.template_name, {"form": form})

        user = form.save()
        user.is_active = False  # can't login until email validation
        user.email_confirmed = False
        user.save()

        send_validation_email(request, user, "Activer votre compte Interludes", self.email_template)

        messages.info(
            request,
            "Un lien vous a été envoyé par mail. Utilisez le pour finaliser la création de compte.",
        )

        return redirect("accounts:login")


class ActivateAccountView(RedirectView):
    """Vue d'activation de compte (lien envoyé par mail)"""

    permanent = False
    success_pattern_name = "profile"
    failure_pattern_name = "home"

    def get_redirect_url(self, uidb64, token, *args, **kwargs):
        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            user = EmailUser.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, EmailUser.DoesNotExist):
            messages.error(
                self.request,
                "Le lien de confirmation d'adresse mail ne correspond à aucun·e utilisateur·ice inscrit·e",
            )
            return reverse(self.failure_pattern_name)

        if not email_token_generator.check_token(user, token):
            messages.error(
                self.request,
                "Le lien de confirmation d'adresse mail est invalide ou déjà utilisé",
            )
            return reverse(self.failure_pattern_name)

        user.is_active = True
        user.email_confirmed = True
        user.save()
        login(self.request, user, backend="django.contrib.auth.backends.ModelBackend")
        messages.success(self.request, "Votre adresse email a bien été confirmée.")
        return reverse(self.success_pattern_name)


# ==============================
# Update personal info
# ==============================


class UpdateAccountView(LoginRequiredMixin, UpdateView):
    """Vue pour la mise à jour des infos personnelles"""

    template_name = "update.html"
    form_class = forms.UpdateAccountForm
    email_template = "email/change.html"

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["update_form"] = context["form"]
        context["password_form"] = forms.UpdatePasswordForm(user=self.request.user)
        return context

    def get_success_url(self):
        assert isinstance(self.request.user, EmailUser)
        if not self.request.user.email_confirmed:
            send_validation_email(
                self.request,
                self.request.user,
                "Valider le changement d'email de votre compte Interludes",
                self.email_template,
            )

            messages.info(
                self.request,
                "Un lien vous a été envoyé par mail. Utilisez le pour valider la mise à jour.",
            )

            # return reverse("registration:email_confirmation_needed")
        return reverse("profile")

    def form_valid(self, form):
        messages.success(self.request, "Informations personnelles mises à jour")
        return super().form_valid(form)


class UpdatePasswordView(LoginRequiredMixin, FormView):
    """Change a user's password"""

    template_name = "update.html"
    form_class = forms.UpdatePasswordForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["password_form"] = context["form"]
        context["update_form"] = forms.UpdateAccountForm(instance=self.request.user)
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def form_valid(self, form):
        assert isinstance(self.request.user, EmailUser)
        form.apply()
        messages.success(self.request, "Mot de passe mis à jour")
        login(self.request, self.request.user, backend="django.contrib.auth.backends.ModelBackend")
        return redirect("profile")


# ==============================
# Reset password
# ==============================


class ResetPasswordView(auth_views.PasswordResetView):
    """Vue pour le gestion du mot de passe oublié"""

    email_template_name = "email/password_reset.html"
    subject_template_name = "email/password_reset.txt"
    success_url = reverse_lazy("accounts:login")
    template_name = "password_reset.html"
    form_class = forms.PasswordResetEmailForm

    def form_valid(self, form):
        messages.info(self.request, "Un email vous a été envoyé avec un lien de réinitialisation")
        return super().form_valid(form)


class ResetPasswordConfirmView(auth_views.PasswordResetConfirmView):
    """Vue demandant de saisir un nouveau mot de passe"""

    success_url = reverse_lazy("accounts:login")
    template_name = "password_reset_confirm.html"

    def form_valid(self, form):
        messages.success(self.request, "Votre mot de passe a été enregistré")
        return super().form_valid(form)


# ==============================
# Delete account
# ==============================


class DeleteConfirmView(LoginRequiredMixin, TemplateView):
    template_name = "delete_account.html"


class DeleteFinalView(LogoutView):
    pattern_name = "home"
    message = "Votre compte a été supprimé"

    def get_redirect_url(self, *args, **kwargs):
        self.user = self.request.user
        next_page = super().get_redirect_url(*args, **kwargs)
        self.user.delete()
        return next_page


# ==============================
# Clipper
# ==============================


class ClipperLoginView(View):
    """CAS authentication view.

    Implement the CAS authentication scheme:

accounts/templates/create_account.html
{% extends "base.html" %}

{% block "content" %}
	<h2>Créer un compte</h2>

	<form method="post" action="{% url 'accounts:create' %}">
		{% csrf_token %}
		{{ form.as_html }}
		<br>
		<div class="flex">
			<input type="submit" value="Valider">
			<a class="button" href="{% url 'accounts:login' %}">Annuler</a>
		</div>
	</form>
{% endblock %}

accounts/templates/delete_account.html
{% extends "base.html" %}

{% block "content" %}
<h2>Supprimer mon compte</h2>

<p>
  Ceci supprimera votre compte et vous désinscrira de l'évènement.
  Si vous avez déjà payé votre inscription, il ne sera pas forcément possible de
  vous rembourser. Contactez-nous le cas échéant.
</p>
<p>
  Si vous avez proposé des activités, celles-ci seront conservées (avec toute
  information de contact ou informations personnelles qu'elles contiennent).
  Si vous voulez supprimer l'activité (ou juste les informations personnelles qu'elle contient),
  n'hésitez pas à nous contacter.
  Nous anonymiserons toutes les activités une fois l'évènement passé.
</p>

<div class="flex">
  <a class="red button" href="{% url 'accounts:delete_final' %}">Supprimer</a>
  <a class="button" href="{% url 'profile' %}">Ne pas supprimer</a>
</div>

{% endblock %}

accounts/templates/login.html
{% extends "base.html" %}

{% block nav_login %}current{% endblock %}

{% block "content" %}
<div id="content-area">
	<h2>Connexion</h2>

	{% if next %}
	<ul class="messagelist">
		{% if user.is_authenticated %}
		<li class="error">Accès non autorisé.</li>
		{% else %}
		<li class="error">Vous devez vous connectez pour accéder à cette page.</li>
		{% endif %}
	</ul>
	{% endif %}

	<a class="fancybutton" href="{% url 'accounts:clipper' %}">Compte clipper (ENS Ulm)</a>

	<div class="fancy"><span>OU</span></div>

	{% if form.errors %}
	<ul class="messagelist">
		<li class="error">Login ou mot de passe incorrect</li>
	</ul>
	{% endif %}

	<form method="post" action="{% url 'accounts:login' %}?next={{ next|urlencode }}">
		{% csrf_token %}
		<table>
			<tr>
				<td>{{ form.username.label_tag }}</td>
				<td>{{ form.username }}</td>
			</tr>
			<tr>
				<td>{{ form.password.label_tag }}</td>
				<td>{{ form.password }}</td>
			</tr>
		</table>
		<a href="{% url 'accounts:password_reset' %}">Mot de passe oublié&nbsp;?</a>
		<br><br>
		<div class="flex">
			<input type="submit" value="Connexion">
			{% if settings.registrations_open %}
			<a class="button" href="{% url 'accounts:create' %}">Créer un compte</a>
			{% endif %}
		</div>
		<input type="hidden" name="next" value="{{ next }}">
	</form>
</div>

{% endblock %}

accounts/templates/password_reset.html
{% extends 'base.html' %}

{% block "content" %}
	<h2>Mot de passe oublié ?</h2>
	<p>Saissisez votre adresse email ci-dessous pour recevoir un lien de réinitialisation du mot de passe.</p>

	<form method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<div class="flex">
			<input type="submit" value="Valider">
			<a class="button" href="{% url 'accounts:login' %}">Annuler</a>
		</div>
	</form>
{% endblock %}

accounts/templates/password_reset_confirm.html
{% extends 'base.html' %}

{% block "content" %}

{% if validlink %}

<h2>Saissisez un nouveau mot de passe</h2>
<form method="POST">
	{% csrf_token %}
	{{ form.as_p }}
	<div class="flex">
		<input type="submit" value="Changer mon mot de passe">
		<a class="button" href="{% url 'accounts:login' %}">Annuler</a>
	</div>
</form>

{% else %}

<h2>Lien invalide</h2>

<p>Le lien de réinitialisation est invalide, peut-être a-t-il déjà été utilisé.
	Veuillez <a href="{% url 'accounts:password_reset' %}">demander un nouveau lien</a>.
</p>

{% endif %}
{% endblock %}

accounts/templates/update.html
{% extends "base.html" %}

{% block "content" %}
	<h2>Changer mes informations</h2>

	<form method="post" action="{% url 'accounts:update' %}">
		{% csrf_token %}
		{{ update_form.as_html }}
		<br>
		<div class="flex">
			<input type="submit" value="Valider">
			<a class="button" href="{% url 'profile' %}">Annuler</a>
		</div>
	</form>

	<h2>Changer mon mot de passe</h2>

	<form method="post" action="{% url 'accounts:change_password' %}">
		{% csrf_token %}
		{{ password_form.as_html }}
		<br>
		<div class="flex">
			<input type="submit" value="Valider">
			<a class="button" href="{% url 'profile' %}">Annuler</a>
		</div>
	</form>
{% endblock %}